using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Schedule1ModdingTool.Models;
using Schedule1ModdingTool.Utils;
using Brush = System.Windows.Media.Brush;
using Brushes = System.Windows.Media.Brushes;
using Color = System.Windows.Media.Color;
using FlowDirection = System.Windows.FlowDirection;
using FontFamily = System.Windows.Media.FontFamily;
using Pen = System.Windows.Media.Pen;
using Point = System.Windows.Point;

namespace Schedule1ModdingTool.Services
{
    /// <summary>
    /// Creates first-pass authoring assets for custom clothing inside the project Resources folder.
    /// </summary>
    public sealed class ClothingStudioService
    {
        public sealed class StudioGenerationResult
        {
            public bool Success { get; init; }
            public string Message { get; init; } = string.Empty;
            public string? RecommendedClothingAssetPath { get; init; }
            public ResourceAsset? PrimaryAsset { get; init; }
            public IReadOnlyList<ResourceAsset> AddedOrUpdatedAssets { get; init; } = Array.Empty<ResourceAsset>();
        }

        public StudioGenerationResult GenerateClothingTemplate(QuestProject project, string projectDirectory, ItemBlueprint item)
        {
            ArgumentNullException.ThrowIfNull(project);
            ArgumentNullException.ThrowIfNull(item);

            var safeKey = BuildSafeKey(item.ItemId);
            var folder = item.ClothingApplicationType switch
            {
                ClothingApplicationTypeOption.BodyLayer => "ClothingStudio/BodyLayers",
                ClothingApplicationTypeOption.FaceLayer => "ClothingStudio/FaceLayers",
                _ => "ClothingStudio/Accessories"
            };

            var relativePath = $"Resources/{folder}/{safeKey}.png";
            var absolutePath = Path.Combine(projectDirectory, relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath)!);

            var title = item.ClothingApplicationType switch
            {
                ClothingApplicationTypeOption.BodyLayer => "Body Layer Template",
                ClothingApplicationTypeOption.FaceLayer => "Face Layer Template",
                _ => "Accessory Texture Sheet"
            };

            var subtitle = item.ClothingApplicationType switch
            {
                ClothingApplicationTypeOption.BodyLayer => "Paint directly over this guide, then export to the same filename.",
                ClothingApplicationTypeOption.FaceLayer => "Use this as a face-overlay guide for custom makeup, tattoos, or masks.",
                _ => "Use this as a texture-planning sheet while the actual accessory mesh is authored outside the tool."
            };

            var accent = GetAccentColor(item.ClothingApplicationType);
            RenderTemplatePng(
                absolutePath,
                1024,
                1024,
                title,
                item.DisplayName,
                subtitle,
                accent,
                item.ClothingApplicationType);

            var asset = AddOrUpdateAsset(
                project,
                relativePath,
                $"{item.DisplayName} Template",
                $"Generated by Clothing Studio for {item.ClothingApplicationType}.");

            return new StudioGenerationResult
            {
                Success = true,
                Message = $"Created clothing template '{asset.RelativePath}'.",
                RecommendedClothingAssetPath = ToS1ApiResourcePath(relativePath),
                PrimaryAsset = asset,
                AddedOrUpdatedAssets = new[] { asset }
            };
        }

        public StudioGenerationResult GenerateIconTemplate(QuestProject project, string projectDirectory, ItemBlueprint item)
        {
            ArgumentNullException.ThrowIfNull(project);
            ArgumentNullException.ThrowIfNull(item);

            var safeKey = BuildSafeKey(item.ItemId);
            var relativePath = $"Resources/ClothingStudio/Icons/{safeKey}_icon.png";
            var absolutePath = Path.Combine(projectDirectory, relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath)!);

            RenderIconTemplatePng(
                absolutePath,
                512,
                512,
                item.DisplayName,
                GetAccentColor(item.ClothingApplicationType));

            var asset = AddOrUpdateAsset(
                project,
                relativePath,
                $"{item.DisplayName} Icon",
                "Generated by Clothing Studio as a square icon starting point.");

            return new StudioGenerationResult
            {
                Success = true,
                Message = $"Created icon template '{asset.RelativePath}'.",
                PrimaryAsset = asset,
                AddedOrUpdatedAssets = new[] { asset }
            };
        }

        public StudioGenerationResult GenerateAccessoryStarterPack(QuestProject project, string projectDirectory, ItemBlueprint item)
        {
            ArgumentNullException.ThrowIfNull(project);
            ArgumentNullException.ThrowIfNull(item);

            var safeKey = BuildSafeKey(item.ItemId);
            var guideRelativePath = $"Resources/ClothingStudio/Accessories/{safeKey}_starter.txt";
            var guideAbsolutePath = Path.Combine(projectDirectory, guideRelativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(guideAbsolutePath)!);
            File.WriteAllText(guideAbsolutePath, BuildAccessoryGuide(item), Encoding.UTF8);

            var templateResult = GenerateClothingTemplate(project, projectDirectory, item);
            var guideAsset = AddOrUpdateAsset(
                project,
                guideRelativePath,
                $"{item.DisplayName} Accessory Guide",
                "Generated by Clothing Studio with a recommended external modelling workflow.");

            var assets = templateResult.PrimaryAsset == null
                ? new[] { guideAsset }
                : new[] { templateResult.PrimaryAsset, guideAsset };

            return new StudioGenerationResult
            {
                Success = true,
                Message = $"Created accessory starter pack for '{item.DisplayName}'.",
                RecommendedClothingAssetPath = templateResult.RecommendedClothingAssetPath,
                PrimaryAsset = templateResult.PrimaryAsset,
                AddedOrUpdatedAssets = assets
            };
        }

        public static string ToS1ApiResourcePath(string? relativePath)
        {
            if (string.IsNullOrWhiteSpace(relativePath))
                return string.Empty;

            var normalized = relativePath.Replace('\\', '/');
            if (normalized.StartsWith("Resources/", StringComparison.OrdinalIgnoreCase))
            {
                normalized = normalized.Substring("Resources/".Length);
            }

            var extension = Path.GetExtension(normalized);
            if (!string.IsNullOrWhiteSpace(extension))
            {
                normalized = normalized.Substring(0, normalized.Length - extension.Length);
            }

            return normalized.Trim('/');
        }

        public StudioGenerationResult ImportTexturePng(
            QuestProject project,
            string projectDirectory,
            ItemBlueprint item,
            byte[] pngBytes,
            string fileSuffix,
            string displayName,
            string notes)
        {
            ArgumentNullException.ThrowIfNull(project);
            ArgumentNullException.ThrowIfNull(item);
            ArgumentNullException.ThrowIfNull(pngBytes);

            var relativePath = BuildTextureRelativePath(item, fileSuffix);
            return SaveTexturePng(project, projectDirectory, relativePath, pngBytes, displayName, notes);
        }

        public StudioGenerationResult SaveTexturePng(
            QuestProject project,
            string projectDirectory,
            string relativePath,
            byte[] pngBytes,
            string displayName,
            string notes)
        {
            ArgumentNullException.ThrowIfNull(project);
            ArgumentNullException.ThrowIfNull(pngBytes);

            if (string.IsNullOrWhiteSpace(relativePath))
            {
                return new StudioGenerationResult
                {
                    Success = false,
                    Message = "Relative resource path is required."
                };
            }

            var normalizedRelativePath = relativePath.Replace('\\', '/').TrimStart('/');
            var absolutePath = Path.Combine(projectDirectory, normalizedRelativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath)!);
            File.WriteAllBytes(absolutePath, pngBytes);

            var asset = AddOrUpdateAsset(project, normalizedRelativePath, displayName, notes);
            return new StudioGenerationResult
            {
                Success = true,
                Message = $"Saved clothing texture '{asset.RelativePath}'.",
                RecommendedClothingAssetPath = ToS1ApiResourcePath(asset.RelativePath),
                PrimaryAsset = asset,
                AddedOrUpdatedAssets = new[] { asset }
            };
        }

        private static ResourceAsset AddOrUpdateAsset(QuestProject project, string relativePath, string displayName, string notes)
        {
            var existing = project.Resources.FirstOrDefault(resource =>
                string.Equals(resource.RelativePath, relativePath, StringComparison.OrdinalIgnoreCase));

            if (existing != null)
            {
                existing.DisplayName = displayName;
                existing.Notes = notes;
                project.MarkAsModified();
                return existing;
            }

            var asset = new ResourceAsset
            {
                DisplayName = displayName,
                RelativePath = relativePath,
                Notes = notes
            };

            project.AddResource(asset);
            return asset;
        }

        private static string BuildSafeKey(string source)
        {
            if (string.IsNullOrWhiteSpace(source))
                return "custom_clothing";

            var sanitized = new string(source
                .Trim()
                .ToLowerInvariant()
                .Select(character => char.IsLetterOrDigit(character) || character == '_' || character == '-'
                    ? character
                    : '_')
                .ToArray())
                .Trim('_');

            return string.IsNullOrWhiteSpace(sanitized) ? "custom_clothing" : sanitized;
        }

        private static string BuildTextureRelativePath(ItemBlueprint item, string fileSuffix)
        {
            var safeKey = BuildSafeKey(item.ItemId);
            var safeSuffix = BuildSafeKey(fileSuffix);
            var folder = item.ClothingApplicationType switch
            {
                ClothingApplicationTypeOption.BodyLayer => "ClothingStudio/BodyLayers",
                ClothingApplicationTypeOption.FaceLayer => "ClothingStudio/FaceLayers",
                _ => "ClothingStudio/Accessories"
            };

            return $"Resources/{folder}/{safeKey}_{safeSuffix}.png";
        }

        private static Color GetAccentColor(ClothingApplicationTypeOption applicationType)
        {
            return applicationType switch
            {
                ClothingApplicationTypeOption.BodyLayer => Color.FromRgb(198, 118, 51),
                ClothingApplicationTypeOption.FaceLayer => Color.FromRgb(77, 160, 211),
                _ => Color.FromRgb(180, 95, 153)
            };
        }

        private static void RenderTemplatePng(
            string outputPath,
            int width,
            int height,
            string title,
            string itemName,
            string subtitle,
            Color accent,
            ClothingApplicationTypeOption applicationType)
        {
            var background = new SolidColorBrush(Color.FromRgb(17, 22, 28));
            var panelBrush = new SolidColorBrush(Color.FromRgb(28, 35, 43));
            var accentBrush = new SolidColorBrush(accent);
            var faintAccentBrush = new SolidColorBrush(Color.FromArgb(45, accent.R, accent.G, accent.B));
            var textBrush = Brushes.White;
            var dimTextBrush = new SolidColorBrush(Color.FromRgb(155, 167, 180));

            var visual = new DrawingVisual();
            using (var context = visual.RenderOpen())
            {
                context.DrawRectangle(background, null, new Rect(0, 0, width, height));
                DrawGrid(context, width, height, faintAccentBrush);

                var innerRect = new Rect(48, 48, width - 96, height - 96);
                context.DrawRoundedRectangle(panelBrush, new Pen(accentBrush, 3), innerRect, 24, 24);

                DrawText(context, title, 42, FontWeights.Bold, textBrush, new Point(84, 84));
                DrawText(context, itemName, 22, FontWeights.SemiBold, accentBrush, new Point(86, 144));
                DrawText(context, subtitle, 18, FontWeights.Normal, dimTextBrush, new Point(86, 188), width - 172);

                var artRect = new Rect(120, 300, width - 240, height - 420);
                context.DrawRoundedRectangle(null, new Pen(accentBrush, 5), artRect, 18, 18);
                context.DrawRectangle(faintAccentBrush, null, new Rect(artRect.X, artRect.Y, artRect.Width, 96));
                DrawText(context, GetCanvasTitle(applicationType), 24, FontWeights.Bold, textBrush, new Point(artRect.X + 28, artRect.Y + 28));
                DrawCrosshair(context, artRect, accentBrush);

                var footerRect = new Rect(84, height - 118, width - 168, 54);
                context.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(22, 28, 35)), new Pen(faintAccentBrush, 1.5), footerRect, 12, 12);
                DrawText(context, "Tip: import this PNG into your editor, paint over the guide, then keep the same runtime path in Clothing Asset Path.", 15, FontWeights.Normal, dimTextBrush, new Point(footerRect.X + 18, footerRect.Y + 17), footerRect.Width - 36);
            }

            var bitmap = new RenderTargetBitmap(width, height, 96, 96, PixelFormats.Pbgra32);
            bitmap.Render(visual);

            var encoder = new PngBitmapEncoder();
            encoder.Frames.Add(BitmapFrame.Create(bitmap));
            using var stream = File.Create(outputPath);
            encoder.Save(stream);
        }

        private static void RenderIconTemplatePng(string outputPath, int width, int height, string itemName, Color accent)
        {
            var background = new SolidColorBrush(Color.FromRgb(20, 24, 29));
            var accentBrush = new SolidColorBrush(accent);
            var softAccentBrush = new SolidColorBrush(Color.FromArgb(70, accent.R, accent.G, accent.B));
            var textBrush = Brushes.White;
            var dimTextBrush = new SolidColorBrush(Color.FromRgb(170, 179, 188));

            var visual = new DrawingVisual();
            using (var context = visual.RenderOpen())
            {
                context.DrawRectangle(background, null, new Rect(0, 0, width, height));
                context.DrawRoundedRectangle(null, new Pen(accentBrush, 6), new Rect(26, 26, width - 52, height - 52), 28, 28);
                context.DrawEllipse(softAccentBrush, new Pen(accentBrush, 4), new Point(width / 2d, height / 2d - 24), 118, 118);
                context.DrawRectangle(new SolidColorBrush(Color.FromArgb(40, 255, 255, 255)), null, new Rect(width / 2d - 26, 118, 52, 200));
                context.DrawEllipse(accentBrush, null, new Point(width / 2d, 168), 38, 38);

                DrawText(context, "ICON", 22, FontWeights.Bold, textBrush, new Point(width / 2d - 34, 350));
                DrawText(context, itemName, 18, FontWeights.SemiBold, textBrush, new Point(52, 392), width - 104);
                DrawText(context, "Replace the placeholder art but keep the square canvas.", 14, FontWeights.Normal, dimTextBrush, new Point(52, 432), width - 104);
            }

            var bitmap = new RenderTargetBitmap(width, height, 96, 96, PixelFormats.Pbgra32);
            bitmap.Render(visual);

            var encoder = new PngBitmapEncoder();
            encoder.Frames.Add(BitmapFrame.Create(bitmap));
            using var stream = File.Create(outputPath);
            encoder.Save(stream);
        }

        private static string BuildAccessoryGuide(ItemBlueprint item)
        {
            var safeKey = BuildSafeKey(item.ItemId);
            var recommendedPath = $"ClothingStudio/Accessories/{safeKey}";

            return
$@"Accessory Starter Pack
======================

Item: {item.DisplayName}
Item ID: {item.ItemId}
Recommended S1API clothing path: {recommendedPath}

Suggested workflow
1. Model and texture the accessory in Blender, Unity, or your DCC of choice.
2. Export or prepare the accessory asset so it can be registered at the path above.
3. Keep the generated texture sheet as a planning board for colors, logos, and material regions.
4. Set Clothing Asset Path in the editor to the final accessory resource path.
5. Generate or replace the icon template so the inventory/shop icon matches the accessory.

Notes
- This tool does not include an in-app 3D modeller.
- The generated accessory texture sheet is a concept/template file, not the final wearable asset.
- Use the Resources folder beside this file as your mod-local authoring scratch area.
";
        }

        private static string GetCanvasTitle(ClothingApplicationTypeOption applicationType)
        {
            return applicationType switch
            {
                ClothingApplicationTypeOption.BodyLayer => "Paint Area",
                ClothingApplicationTypeOption.FaceLayer => "Overlay Area",
                _ => "Concept / Texture Area"
            };
        }

        private static void DrawGrid(DrawingContext context, int width, int height, Brush brush)
        {
            var pen = new Pen(brush, 1);
            const int spacing = 64;

            for (var x = spacing; x < width; x += spacing)
            {
                context.DrawLine(pen, new Point(x, 0), new Point(x, height));
            }

            for (var y = spacing; y < height; y += spacing)
            {
                context.DrawLine(pen, new Point(0, y), new Point(width, y));
            }
        }

        private static void DrawCrosshair(DrawingContext context, Rect rect, Brush brush)
        {
            var pen = new Pen(brush, 2);
            var centerX = rect.X + (rect.Width / 2d);
            var centerY = rect.Y + (rect.Height / 2d);
            context.DrawLine(pen, new Point(centerX, rect.Y), new Point(centerX, rect.Bottom));
            context.DrawLine(pen, new Point(rect.X, centerY), new Point(rect.Right, centerY));
        }

        private static void DrawText(
            DrawingContext context,
            string text,
            double fontSize,
            FontWeight fontWeight,
            Brush brush,
            Point origin,
            double? maxTextWidth = null)
        {
            var formattedText = new FormattedText(
                text,
                CultureInfo.InvariantCulture,
                FlowDirection.LeftToRight,
                new Typeface(new FontFamily("Segoe UI"), FontStyles.Normal, fontWeight, FontStretches.Normal),
                fontSize,
                brush,
                1.0);

            if (maxTextWidth.HasValue)
            {
                formattedText.MaxTextWidth = maxTextWidth.Value;
            }

            context.DrawText(formattedText, origin);
        }
    }
}
